package hs.kr.entrydsm.global.exception

/**
 * 시스템 전반에서 사용되는 도메인 오류 코드를 정의하는 열거형입니다.
 *
 * 각 도메인별로 고유한 오류 코드를 가지며, 오류의 원인과 해결 방안을 명확히 식별할 수 있도록
 * 체계적으로 분류되어 있습니다. 코드 체계는 도메인별 접두사를 사용합니다.
 *
 * @property code 고유한 오류 코드 (예: LEX001, PAR002)
 * @property description 오류에 대한 한국어 설명
 *
 * @see <a href="https://devblog.kakaostyle.com/ko/2025-03-21-1-domain-driven-hexagonal-architecture-by-example/">코드 사례로 보는 Domain-Driven 헥사고날 아키텍처</a>
 *
 * @author kangeunchan
 * @since 2025.07.15
 */
enum class ErrorCode(val code: String, val description: String) {
    // 공통 오류 (CMN)
    UNKNOWN_ERROR("CMN001", "알 수 없는 오류가 발생했습니다"),
    VALIDATION_FAILED("CMN002", "유효성 검사에 실패했습니다"),
    BUSINESS_RULE_VIOLATION("CMN003", "비즈니스 규칙을 위반했습니다"),
    INTERNAL_SERVER_ERROR("CMN004", "서버 내부 오류가 발생했습니다"),
    UNEXPECTED_ERROR("CMN005", "예상치 못한 오류가 발생했습니다"),

    // Lexer 도메인 오류 (LEX)
    UNEXPECTED_CHARACTER("LEX001", "예상치 못한 문자가 발견되었습니다"),
    UNCLOSED_VARIABLE("LEX002", "변수가 닫히지 않았습니다"),
    INVALID_NUMBER_FORMAT("LEX003", "잘못된 숫자 형식입니다"),
    INVALID_TOKEN_SEQUENCE("LEX004", "잘못된 토큰 시퀀스입니다"),
    TOKEN_VALUE_EMPTY_EXCEPT_EOF("LEX005", "토큰 값은 비어있을 수 없습니다(EOF 제외)"),
    LEXER_VARIABLE_NAME_EMPTY("LEX006", "변수명은 비어있을 수 없습니다"),
    NOT_OPERATOR_TYPE("LEX007", "연산자 타입이 아닙니다"),
    NOT_NUMBER_TOKEN("LEX008", "숫자 토큰이 아닙니다"),
    NOT_BOOLEAN_TOKEN("LEX009", "불린 토큰이 아닙니다"),
    UNEXPECTED_BOOLEAN_TOKEN_TYPE("LEX010", "예상치 못한 불린 토큰 타입입니다"),
    INVALID_IDENTIFIER_FORMAT("LEX011", "유효하지 않은 식별자 형식입니다"),
    INVALID_IDENTIFIER("LEX012", "유효하지 않은 식별자입니다"),
    INVALID_VARIABLE_NAME("LEX013", "유효하지 않은 변수명입니다"),
    LEXER_UNSUPPORTED_OPERATOR("LEX014", "지원하지 않는 연산자입니다"),
    UNSUPPORTED_DELIMITER("LEX015", "지원하지 않는 구분자입니다"),
    LEXER_INVALID_BOOLEAN_VALUE("LEX016", "유효하지 않은 불린 값입니다"),
    UNRECOGNIZED_TOKEN_VALUE("LEX017", "인식할 수 없는 토큰 값입니다"),
    NUMBER_TOKEN_INVALID_NUMBER("LEX018", "NUMBER 타입 토큰 값이 유효한 숫자가 아닙니다"),
    IDENTIFIER_TOKEN_INVALID("LEX019", "IDENTIFIER 타입 토큰 값이 유효한 식별자가 아닙니다"),
    VARIABLE_TOKEN_INVALID("LEX020", "VARIABLE 타입 토큰 값이 유효한 변수명이 아닙니다"),
    BOOLEAN_TOKEN_INVALID("LEX021", "불린 타입 토큰 값이 유효하지 않습니다"),
    UNALLOWED_CHARACTER("LEX022", "허용되지 않은 문자입니다"),
    TOKENS_EMPTY("LEX023", "검증할 토큰 목록이 비어있습니다"),
    TOKEN_TYPE_MISMATCH("LEX024", "토큰 타입이 기대와 일치하지 않습니다"),
    NUMBER_NOT_FINITE("LEX025", "숫자 값이 유한하지 않습니다"),
    NUMBER_OUT_OF_RANGE("LEX026", "숫자 값이 허용 범위를 벗어났습니다"),
    NOT_IDENTIFIER_TOKEN("LEX027", "식별자 토큰이 아닙니다"),
    IDENTIFIER_EMPTY("LEX028", "식별자 값이 비어있습니다"),
    IDENTIFIER_TOO_LONG("LEX029", "식별자 길이가 제한을 초과했습니다"),
    IDENTIFIER_INVALID_FORMAT("LEX030", "유효하지 않은 식별자 형식입니다"),
    NOT_VARIABLE_TOKEN("LEX031", "변수 토큰이 아닙니다"),
    VARIABLE_NAME_TOO_LONG("LEX032", "변수명 길이가 제한을 초과했습니다"),
    VARIABLE_NAME_INVALID_FORMAT("LEX033", "유효하지 않은 변수명 형식입니다"),
    OPERATOR_VALUE_EMPTY("LEX034", "연산자 값이 비어있습니다"),
    NOT_KEYWORD_TOKEN("LEX035", "키워드 토큰이 아닙니다"),
    TOKEN_TOO_LONG("LEX036", "토큰 길이가 제한을 초과했습니다"),
    INVALID_OPERATOR_SEQUENCE("LEX037", "유효하지 않은 연산자 시퀀스입니다"),
    MULTIPLE_EOF_TOKENS("LEX038", "EOF 토큰이 여러 개 존재합니다"),
    EOF_NOT_AT_END("LEX039", "EOF 토큰이 마지막 위치에 있지 않습니다"),
    DOLLAR_TOKEN_INVALID_VALUE("LEX040", "EOF 타입이지만 '$' 값이 아닙니다"),
    NUMBER_TOKEN_NOT_NUMERIC("LEX041", "NUMBER 타입이지만 숫자가 아닙니다"),
    KEYWORD_VALUE_MISMATCH("LEX042", "키워드 값이 기대와 일치하지 않습니다"),
    INPUT_LENGTH_EXCEEDED("LEX043", "입력 길이가 제한을 초과했습니다"),
    DISALLOWED_CHARACTER("LEX044", "허용되지 않은 문자가 포함되었습니다"),
    FORBIDDEN_CONTROL_CHARACTER("LEX045", "금지된 제어 문자가 포함되었습니다"),
    LINE_COUNT_EXCEEDED("LEX046", "라인 수가 제한을 초과했습니다"),
    LINE_LENGTH_EXCEEDED("LEX047", "라인 길이가 제한을 초과했습니다"),
    BOM_CHARACTER_DETECTED("LEX048", "BOM 문자가 감지되었습니다"),
    NULL_CHARACTER_DETECTED("LEX049", "널 문자가 포함되어 있습니다"),
    MAX_NESTING_DEPTH_EXCEEDED("LEX050", "중첩 깊이가 제한을 초과했습니다"),
    EXCESSIVE_WHITESPACE_DETECTED("LEX051", "과도한 연속 공백이 감지되었습니다"),
    SUSPICIOUS_REPEAT_PATTERN("LEX052", "의심스러운 반복 패턴이 감지되었습니다"),
    INVALID_POSITION_INDEX("LEX053", "위치 인덱스가 유효하지 않습니다"),
    INVALID_POSITION_LINE("LEX054", "라인 번호가 유효하지 않습니다"),
    INVALID_POSITION_COLUMN("LEX055", "열 번호가 유효하지 않습니다"),
    INVALID_MAX_TOKEN_LENGTH("LEX056", "최대 토큰 길이 값이 유효하지 않습니다"),
    MAX_TOKEN_LENGTH_EXCEEDED("LEX057", "최대 토큰 길이가 제한을 초과했습니다"),
    MAX_TOKEN_LENGTH_INVALID("LEX058", "최대 토큰 길이는 1 이상이어야 합니다"),
    START_TIME_INVALID("LEX059", "시작 시간이 유효하지 않습니다"),
    STEPS_NEGATIVE("LEX060", "이동 거리는 0 이상이어야 합니다"),
    INVALID_LEXING_RESULT_ERROR_STATE("LEX061", "실패한 LexingResult는 반드시 error 정보를 포함해야 합니다"),
    NEGATIVE_ANALYSIS_DURATION("LEX062", "분석 소요 시간은 0 이상이어야 합니다"),
    NEGATIVE_INPUT_LENGTH("LEX063", "입력 텍스트 길이는 0 이상이어야 합니다"),
    NEGATIVE_TOKEN_COUNT("LEX064", "토큰 개수는 0 이상이어야 합니다"),
    INVALID_POSITION_ORDER("LEX065", "시작 위치가 끝 위치보다 늦을 수 없습니다"),
    NEGATIVE_TOKEN_LENGTH("LEX066", "토큰 길이는 0 이상이어야 합니다"),
    NEGATIVE_ADDITIONAL_LENGTH("LEX067", "추가 길이는 0 이상이어야 합니다"),

    // Parser 도메인 오류 (PAR)
    SYNTAX_ERROR("PAR001", "구문 오류가 발생했습니다"),
    GOTO_ERROR("PAR002", "GOTO 상태 전이 오류입니다"),
    LR_PARSING_ERROR("PAR003", "LR 파싱 중 오류가 발생했습니다"),
    GRAMMAR_CONFLICT("PAR004", "문법 충돌이 발생했습니다"),
    UNEXPECTED_END_OF_INPUT("PAR005", "예상치 못한 입력 종료입니다"),
    INVALID_AST_NODE("PAR006", "잘못된 AST 노드입니다"),
    STACK_OVERFLOW("PAR007", "파서 스택 오버플로가 발생했습니다"),
    INCOMPLETE_INPUT("PAR008", "불완전한 입력입니다"),
    PARSING_ERROR("PAR009", "파싱 오류가 발생했습니다"),
    INVALID_GRAMMAR("PAR010", "문법 정의가 유효하지 않습니다"),
    EMPTY_PRODUCTIONS("PAR011", "생산 규칙이 비어있습니다"),
    EMPTY_TERMINALS("PAR012", "터미널 심볼이 비어있습니다"),
    EMPTY_NON_TERMINALS("PAR013", "논터미널 심볼이 비어있습니다"),
    INVALID_START_SYMBOL("PAR014", "시작 심볼은 논터미널이어야 합니다"),
    MAX_DEPTH_NON_POSITIVE("PAR015", "최대 파싱 깊이는 양수여야 합니다"),
    MAX_DEPTH_EXCEEDS_LIMIT("PAR016", "최대 파싱 깊이가 한계를 초과했습니다"),
    CORE_ITEMS_EMPTY("PAR017", "Core 아이템 집합이 비어있습니다"),
    ITEMS_EMPTY("PAR018", "아이템 집합이 비어있습니다"),
    LALR_MERGE_CONFLICT("PAR019", "LALR 병합이 불가능합니다"),
    DOT_POSITION_NEGATIVE("PAR020", "점의 위치는 0 이상이어야 합니다"),
    DOT_POSITION_EXCEEDS_LENGTH("PAR021", "점의 위치가 생성 규칙 길이를 초과했습니다"),
    LOOKAHEAD_NOT_TERMINAL("PAR022", "선행 심볼은 터미널이어야 합니다"),
    ITEM_ALREADY_COMPLETE("PAR023", "완료된 아이템의 점은 더 이상 이동할 수 없습니다"),
    ITEM_SET_MERGE_CONFLICT("PAR024", "아이템 집합 병합이 불가능합니다"),
    STATE_ID_NEGATIVE("PAR025", "상태 ID는 0 이상이어야 합니다"),
    STATE_ITEMS_EMPTY("PAR026", "파싱 상태는 최소 하나의 LR 아이템을 포함해야 합니다"),
    ACCEPTING_MUST_BE_FINAL("PAR027", "수락 상태는 반드시 최종 상태여야 합니다"),
    TRANSITION_UNAVAILABLE("PAR028", "해당 심볼로 전이할 수 없습니다"),
    NOT_TERMINAL_SYMBOL("PAR029", "터미널 심볼이 아닙니다"),
    NOT_NON_TERMINAL_SYMBOL("PAR030", "논터미널 심볼이 아닙니다"),
    PRODUCTION_ID_BELOW_MIN("PAR031", "생성 규칙 ID는 -1 이상이어야 합니다"),
    PRODUCTION_LEFT_NOT_NON_TERMINAL("PAR032", "생성 규칙의 좌변은 논터미널이어야 합니다"),
    PRODUCTION_RIGHT_EMPTY("PAR033", "생성 규칙의 우변은 비어있을 수 없습니다 (엡실론 생성 제외)"),
    PRODUCTION_POSITION_OUT_OF_RANGE("PAR034", "위치가 범위를 벗어났습니다"),
    PRODUCTION_END_POSITION_NEGATIVE("PAR035", "끝 위치는 0 이상이어야 합니다"),
    PRODUCTION_END_POSITION_EXCEEDS("PAR036", "끝 위치가 범위를 벗어났습니다"),
    PRODUCTION_START_POSITION_NEGATIVE("PAR037", "시작 위치는 0 이상이어야 합니다"),
    PRODUCTION_START_POSITION_EXCEEDS("PAR038", "시작 위치가 범위를 벗어났습니다"),
    AST_BUILDER_VALIDATION_FAILED("PAR039", "AST 빌더 검증에 실패했습니다"),
    NOT_ARITHMETIC_OPERATOR("PAR040", "산술 연산자가 아닙니다"),
    UNSUPPORTED_ARITHMETIC_OPERATOR("PAR041", "지원하지 않는 산술 연산자입니다"),
    NOT_LOGICAL_OPERATOR("PAR042", "논리 연산자가 아닙니다"),
    UNSUPPORTED_LOGICAL_OPERATOR("PAR043", "지원하지 않는 논리 연산자입니다"),
    NOT_COMPARISON_OPERATOR("PAR044", "비교 연산자가 아닙니다"),
    UNSUPPORTED_COMPARISON_OPERATOR("PAR045", "지원하지 않는 비교 연산자입니다"),
    NOT_LITERAL_TOKEN("PAR046", "리터럴 토큰이 아닙니다"),
    UNSUPPORTED_LITERAL_TYPE("PAR047", "지원하지 않는 리터럴 타입입니다"),
    BUILDER_NAME_BLANK("PAR048", "빌더 이름은 비어있을 수 없습니다"),
    OPERATOR_BLANK("PAR049", "연산자는 비어있을 수 없습니다"),
    OPERATOR_TOO_LONG("PAR050", "연산자 길이가 너무 깁니다"),
    KERNEL_DOT_POSITION_INVALID("PAR051", "커널 아이템의 점 위치는 0보다 커야 합니다 (확장 생산 규칙 제외)"),
    START_ITEM_MUST_USE_AUGMENTED("PAR052", "시작 아이템은 확장 생산 규칙을 사용해야 합니다"),
    PRODUCTION_LENGTH_EXCEEDS_LIMIT("PAR053", "생산 규칙이 최대 길이를 초과했습니다"),
    LOOKAHEAD_SIZE_EXCEEDS_LIMIT("PAR054", "전방탐색 심볼 개수가 한도를 초과했습니다"),
    INPUT_BLANK("PAR055", "입력이 비어있을 수 없습니다"),
    ACTION_SHIFT_STATE_REQUIRED("PAR056", "Shift 액션에는 상태 번호가 필요합니다"),
    ACTION_REDUCE_PRODUCTION_REQUIRED("PAR057", "Reduce 액션에는 생산 규칙이 필요합니다"),
    UNSUPPORTED_ACTION_TYPE("PAR058", "지원하지 않는 액션 타입입니다"),
    ACCEPTING_STATE_ITEMS_NOT_COMPLETE("PAR059", "수락 상태는 완성된 아이템들만 포함해야 합니다"),
    STATE_COUNT_EXCEEDS_LIMIT("PAR060", "상태 개수가 최대값을 초과했습니다"),
    ITEMS_PER_STATE_EXCEEDS_LIMIT("PAR061", "상태의 아이템 개수가 최대값을 초과했습니다"),
    ACTION_TABLE_CONTAINS_NON_TERMINAL("PAR062", "액션 테이블에 비터미널 심볼이 있습니다"),
    GOTO_TABLE_CONTAINS_TERMINAL("PAR063", "Goto 테이블에 터미널 심볼이 있습니다"),
    TARGET_STATE_NEGATIVE("PAR064", "목표 상태 ID가 음수입니다"),
    TRANSITIONS_PER_STATE_EXCEEDS_LIMIT("PAR065", "전이 개수가 최대값을 초과했습니다"),
    NOT_OPERATOR_SYMBOL("PAR066", "연산자 심볼이 아닙니다"),
    INVALID_BNF_FORMAT("PAR067", "잘못된 BNF 형식입니다"),
    PRODUCTION_COUNT_EXCEEDS_LIMIT("PAR068", "생산 규칙 개수가 최대값을 초과했습니다"),
    UNKNOWN_TOKEN_TYPE("PAR069", "알 수 없는 토큰 타입입니다"),
    ASSOCIATIVITY_OPERATOR_MISMATCH("PAR070", "결합성 규칙의 연산자와 토큰 타입이 일치해야 합니다"),
    LEFT_RECURSION_DETECTED("PAR071", "좌재귀가 감지되었습니다"),
    UNREACHABLE_NON_TERMINALS("PAR072", "도달 불가능한 논터미널들입니다"),
    UNDEFINED_NON_TERMINALS("PAR073", "정의되지 않은 논터미널들입니다"),
    AMBIGUOUS_GRAMMAR_RULE("PAR074", "모호한 문법 규칙이 감지되었습니다"),
    CYCLIC_GRAMMAR_REFERENCE("PAR075", "순환 참조가 감지되었습니다"),
    PRODUCTION_COUNT_BELOW_MIN("PAR076", "생산 규칙이 최소 개수보다 적습니다"),
    START_SYMBOL_NOT_IN_NON_TERMINALS("PAR077", "시작 심볼이 논터미널 집합에 포함되지 않습니다"),
    TERMINALS_NON_TERMINALS_OVERLAP("PAR078", "터미널과 논터미널 집합이 겹칩니다"),
    DUPLICATE_PRODUCTIONS("PAR079", "중복된 생산 규칙이 존재합니다"),
    PRODUCTION_ID_NEGATIVE("PAR080", "생산 규칙 ID가 음수입니다"),
    UNKNOWN_SYMBOL_IN_PRODUCTION("PAR081", "알 수 없는 심볼이 생산 규칙에 사용되었습니다"),
    LALR_STATES_CANNOT_MERGE("PAR082", "상태들을 LALR로 병합할 수 없습니다"),
    NO_STATES_TO_MERGE("PAR083", "병합할 상태가 없습니다"),
    CONFLICT_RESOLUTION_EXCEEDED("PAR084", "충돌 해결이 최대 시도 횟수를 초과했습니다"),
    SHIFT_REDUCE_CONFLICT("PAR085", "Shift/Reduce 충돌이 발생했습니다"),
    REDUCE_REDUCE_CONFLICT_UNRESOLVABLE("PAR086", "Reduce/Reduce 충돌을 해결할 수 없습니다"),
    NON_ASSOCIATIVE_OPERATOR_CONFLICT("PAR087", "비결합 연산자 충돌이 발생했습니다"),
    PRODUCTION_ID_ONLY_FOR_REDUCE("PAR088", "Reduce 액션만이 생산 규칙 ID를 가집니다"),
    FIRST_SET_NOT_CONVERGING("PAR089", "FIRST 집합 계산이 수렴하지 않습니다"),
    FOLLOW_SET_NOT_CONVERGING("PAR090", "FOLLOW 집합 계산이 수렴하지 않습니다"),
    AUGMENTED_PRODUCTION_NOT_FOUND("PAR091", "확장 생산 규칙을 찾을 수 없습니다"),
    LR_CONFLICT_DETECTED("PAR092", "Reduce/Reduce 또는 Shift/Reduce 충돌이 감지되었습니다"),
    NUM_STATES_NOT_POSITIVE("PAR093", "상태 수는 0보다 커야 합니다"),
    NUM_TERMINALS_NOT_POSITIVE("PAR094", "터미널 수는 0보다 커야 합니다"),
    NUM_NON_TERMINALS_NOT_POSITIVE("PAR095", "논터미널 수는 0보다 커야 합니다"),
    MAX_PARSING_DEPTH_NOT_POSITIVE("PAR096", "최대 파싱 깊이는 양수여야 합니다"),
    MAX_PARSING_DEPTH_EXCEEDS_LIMIT("PAR097", "최대 파싱 깊이가 한계를 초과했습니다"),
    TOKEN_COUNT_EXCEEDS_LIMIT("PAR098", "토큰 개수가 최대값을 초과했습니다"),
    MAX_STACK_SIZE_NOT_POSITIVE("PAR099", "최대 스택 크기는 양수여야 합니다"),
    TOKEN_SEQUENCE_EXCEEDS_LIMIT("PAR100", "토큰 시퀀스가 최대 길이를 초과했습니다"),
    NESTING_DEPTH_EXCEEDS_LIMIT("PAR101", "중첩 깊이가 최대값을 초과했습니다"),
    EXPRESSION_COMPLEXITY_EXCEEDS_LIMIT("PAR102", "표현식 복잡도가 최대값을 초과했습니다"),
    OPERATOR_TOKEN_REQUIRED("PAR103", "연산자 토큰이어야 합니다"),
    PRECEDENCE_NEGATIVE("PAR104", "우선순위는 0 이상이어야 합니다"),
    UNKNOWN_ASSOCIATIVITY_SYMBOL("PAR105", "알 수 없는 결합성 심볼입니다"),
    PRODUCTION_ID_OUT_OF_RANGE("PAR106", "생성 규칙 ID가 범위를 벗어났습니다"),
    PRODUCTION_NOT_FOUND("PAR107", "생성 규칙을 찾을 수 없습니다"),
    SYMBOL_NOT_NON_TERMINAL("PAR108", "논터미널 심볼이 필요합니다"),
    GRAMMAR_INVALID("PAR109", "문법이 유효하지 않습니다"),
    NOT_REDUCE_ACTION("PAR110", "Reduce 액션이 아닙니다"),
    TOKEN_VALUE_EMPTY("PAR112", "토큰의 값은 비어있을 수 없습니다"),
    ARGUMENTS_EMPTY("PAR113", "인수 목록은 비어있을 수 없습니다"),
    ARGUMENT_INDEX_OUT_OF_RANGE("PAR114", "인수 인덱스가 범위를 벗어났습니다"),
    UNSUPPORTED_OBJECT_TYPE("PAR115", "지원하지 않는 타입입니다"),
    FAILED_RESULT_MISSING_ERROR("PAR116", "실패한 ParsingResult는 반드시 error 정보를 포함해야 합니다"),
    DURATION_NEGATIVE("PAR117", "분석 소요 시간은 0 이상이어야 합니다"),
    TOKEN_COUNT_NEGATIVE("PAR118", "토큰 개수는 0 이상이어야 합니다"),
    NODE_COUNT_NEGATIVE("PAR119", "노드 개수는 0 이상이어야 합니다"),
    MAX_DEPTH_NEGATIVE("PAR120", "최대 깊이는 0 이상이어야 합니다"),
    SUCCESS_RESULT_MISSING_AST("PAR121", "성공한 ParsingResult는 반드시 AST를 포함해야 합니다"),
    INVALID_STATE_ID("PAR122", "유효하지 않은 상태 ID입니다"),
    STATE_NOT_FOUND("PAR123", "상태를 찾을 수 없습니다"),
    TERMINAL_SYMBOL_REQUIRED("PAR124", "터미널 심볼이 필요합니다"),
    NON_TERMINAL_SYMBOL_REQUIRED("PAR125", "논터미널 심볼이 필요합니다"),

    // AST 도메인 오류 (AST)
    AST_BUILD_ERROR("AST001", "AST 빌드 중 오류가 발생했습니다"),
    NOT_AST_NODE("AST002", "AST 노드가 아닙니다"),
    UNSUPPORTED_AST_TYPE("AST003", "지원하지 않는 AST 타입입니다"),
    INVALID_NODE_STRUCTURE("AST004", "잘못된 노드 구조입니다"),
    AST_VALIDATION_FAILED("AST005", "AST 검증에 실패했습니다"),
    AST_OPTIMIZATION_FAILED("AST006", "AST 최적화에 실패했습니다"),
    AST_TRAVERSAL_ERROR("AST007", "AST 순회 중 오류가 발생했습니다"),
    AST_TYPE_MISMATCH("AST008", "AST 타입이 일치하지 않습니다"),
    AST_SIZE_EXCEEDED("AST009", "AST 크기가 제한을 초과했습니다"),
    AST_DEPTH_EXCEEDED("AST010", "AST 깊이가 제한을 초과했습니다"),
    INVALID_ROOT_NODE("AST011", "AST 루트 노드가 유효하지 않습니다"),
    INVALID_REPLACEMENT_NODE("AST012", "교체할 노드가 유효하지 않습니다"),
    AST_ARGUMENT_COUNT_EXCEEDED("AST013", "인수 개수가 최대 허용량을 초과했습니다"),
    AST_INDEX_OUT_OF_RANGE("AST014", "인덱스가 범위를 벗어났습니다"),
    AST_OPERATOR_EMPTY("AST015", "연산자는 비어있을 수 없습니다"),
    AST_UNSUPPORTED_OPERATOR("AST016", "지원하지 않는 연산자입니다"),
    AST_OPERATOR_NOT_COMMUTATIVE("AST017", "교환법칙이 성립하지 않는 연산자입니다"),
    INVALID_BOOLEAN_VALUE("AST018", "잘못된 불린 값입니다"),
    AST_FUNCTION_NAME_EMPTY("AST019", "함수명은 비어있을 수 없습니다"),
    AST_INVALID_FUNCTION_NAME("AST020", "유효하지 않은 함수명입니다"),
    AST_ARGUMENTS_EMPTY("AST021", "인수가 없습니다"),
    AST_IF_NOT_SIMPLIFIABLE("AST022", "단순화할 수 없는 IF 노드입니다"),
    AST_SIMPLIFICATION_UNEXPECTED_CASE("AST023", "예상치 못한 단순화 케이스"),
    AST_NON_FINITE_NUMBER("AST024", "숫자 값은 유한해야 합니다"),
    AST_NON_INTEGER_TO_INT("AST025", "정수가 아닌 값을 정수로 변환할 수 없습니다"),
    AST_NON_INTEGER_TO_LONG("AST026", "정수가 아닌 값을 Long으로 변환할 수 없습니다"),
    AST_DIVISION_BY_ZERO("AST027", "0으로 나눌 수 없습니다"),
    AST_UNSUPPORTED_UNARY_OPERATOR("AST028", "지원하지 않는 단항 연산자입니다"),
    AST_DOUBLE_NEGATION_NOT_SIMPLIFIABLE("AST029", "이중 음수를 단순화할 수 없습니다"),
    AST_DOUBLE_LOGICAL_NEGATION_NOT_SIMPLIFIABLE("AST030", "이중 논리 부정을 단순화할 수 없습니다"),
    AST_VARIABLE_NAME_EMPTY("AST031", "변수명은 비어있을 수 없습니다"),
    AST_INVALID_VARIABLE_NAME("AST032", "유효하지 않은 변수명입니다"),
    AST_VARIABLE_NOT_BRACKETED("AST033", "변수는 중괄호로 둘러싸여야 합니다"),
    AST_INVALID_NUMBER_LITERAL("AST034", "유효하지 않은 숫자 형식입니다"),
    AST_NOT_ARITHMETIC_OPERATOR("AST035", "산술 연산자가 아닙니다"),
    AST_NOT_COMPARISON_OPERATOR("AST036", "비교 연산자가 아닙니다"),
    AST_NOT_LOGICAL_OPERATOR("AST037", "논리 연산자가 아닙니다"),
    AST_UNSUPPORTED_MATH_FUNCTION("AST038", "지원되지 않는 수학 함수입니다"),
    AST_ARGS_MULTIPLE_CHILDREN_MISMATCH("AST039", "ArgsMultiple 빌더 자식 개수가 잘못되었습니다"),
    AST_ARGS_SINGLE_CHILD_MISMATCH("AST040", "ArgsSingle 빌더 자식 개수가 잘못되었습니다"),
    AST_BINARY_CHILDREN_INSUFFICIENT("AST041", "BinaryOp 빌더 자식 개수가 부족합니다"),
    AST_FUNCTION_CALL_CHILDREN_MISMATCH("AST042", "FunctionCall 빌더 자식 개수가 잘못되었습니다"),
    AST_FUNCTION_CALL_FIRST_NOT_TOKEN("AST043", "FunctionCall 빌더의 첫 번째 자식은 Token이어야 합니다"),
    AST_FUNCTION_CALL_THIRD_NOT_LIST("AST044", "FunctionCall 빌더의 세 번째 자식은 List여야 합니다"),
    AST_FUNCTION_CALL_ARGS_NOT_AST_NODE("AST045", "FunctionCall 빌더의 인수 목록은 ASTNode여야 합니다"),
    AST_FUNCTION_CALL_EMPTY_CHILDREN_MISMATCH("AST046", "FunctionCallEmpty 빌더의 자식 개수가 예상과 다릅니다"),
    AST_FUNCTION_CALL_EMPTY_FIRST_NOT_TOKEN("AST047", "FunctionCallEmpty 빌더의 첫 번째 자식이 Token이 아닙니다"),
    AST_FUNCTION_CALL_EMPTY_SECOND_NOT_TOKEN("AST048", "FunctionCallEmpty 빌더의 두 번째 자식이 Token이 아닙니다"),
    AST_FUNCTION_CALL_EMPTY_THIRD_NOT_TOKEN("AST049", "FunctionCallEmpty 빌더의 세 번째 자식이 Token이 아닙니다"),
    AST_IDENTITY_CHILDREN_EMPTY("AST050", "Identity 빌더 자식이 비어 있습니다"),
    AST_IF_CHILDREN_MISMATCH("AST051", "If 빌더 자식 개수가 올바르지 않습니다"),
    AST_NUMBER_CHILDREN_MISMATCH("AST052", "Number 빌더 자식 개수가 올바르지 않습니다"),
    AST_PARENTHESIZED_CHILDREN_MISMATCH("AST053", "Parenthesized 빌더 자식 개수가 올바르지 않습니다"),
    AST_PARENTHESIZED_SECOND_NOT_AST("AST054", "Parenthesized 빌더 두 번째 자식이 ASTNode 타입이 아닙니다"),
    AST_START_CHILDREN_MISMATCH("AST055", "Start 빌더 자식 개수가 올바르지 않습니다"),
    AST_UNARY_CHILDREN_INSUFFICIENT("AST056", "UnaryOp 빌더 자식 개수가 부족합니다"),
    AST_VARIABLE_CHILDREN_MISMATCH("AST057", "Variable 빌더 자식 개수가 올바르지 않습니다"),
    AST_VARIABLE_FIRST_NOT_TOKEN("AST058", "Variable 빌더 첫 번째 자식이 Token 타입이 아닙니다"),
    AST_NUMBER_IS_NAN("AST059", "숫자 값은 NaN이 될 수 없습니다"),
    AST_NUMBER_TOO_SMALL("AST060", "숫자 값이 최소값 미만입니다"),
    AST_NUMBER_TOO_LARGE("AST061", "숫자 값이 최대값을 초과합니다"),
    AST_VARIABLE_NAME_TOO_LONG("AST062", "변수명이 최대 길이를 초과합니다"),
    AST_VARIABLE_RESERVED_WORD("AST063", "예약어는 변수명으로 사용할 수 없습니다"),
    AST_UNSUPPORTED_BINARY_OPERATOR("AST064", "지원되지 않는 이항 연산자입니다"),
    AST_MODULO_BY_ZERO("AST065", "0으로 나눈 나머지를 구할 수 없습니다"),
    AST_ZERO_POWER_ZERO_UNDEFINED("AST066", "0^0은 정의되지 않습니다"),
    AST_LOGICAL_INCOMPATIBLE_OPERAND("AST067", "논리 연산자는 논리적으로 호환되는 피연산자만 허용합니다"),
    AST_FUNCTION_NAME_TOO_LONG("AST068", "함수명이 최대 길이를 초과합니다"),
    AST_FUNCTION_ARGUMENTS_EXCEEDED("AST069", "함수 인수 개수가 최대값을 초과합니다"),
    AST_FUNCTION_ARGUMENT_COUNT_MISMATCH("AST070", "함수 인수 개수가 요구사항과 일치하지 않습니다"),
    AST_IF_TOTAL_DEPTH_EXCEEDED("AST071", "조건문의 총 깊이가 최대값을 초과합니다"),
    AST_ARGUMENTS_EXCEEDED("AST072", "인수 개수가 최대값을 초과합니다"),
    AST_ARGUMENTS_DUPLICATED("AST073", "중복된 인수가 발견되었습니다"),
    AST_NODE_SIZE_EXCEEDED("AST074", "노드 크기가 최대값을 초과합니다"),
    AST_NODE_DEPTH_EXCEEDED("AST075", "노드 깊이가 최대값을 초과합니다"),
    AST_NODE_VARIABLES_EXCEEDED("AST076", "노드의 변수 개수가 최대값을 초과합니다"),
    AST_TREE_DEPTH_NEGATIVE("AST077", "트리 깊이는 0 이상이어야 합니다"),
    AST_TREE_DEPTH_TOO_LARGE("AST078", "트리 깊이가 최대값을 초과합니다"),
    AST_RUNTIME_RULE_NOT_SUPPORTED("AST079", "현재 버전에서는 런타임 규칙 추가를 지원하지 않습니다"),
    AST_NODE_SIZE_NEGATIVE("AST080", "노드 크기는 0 이상이어야 합니다"),
    AST_NODE_SIZE_TOO_LARGE("AST081", "노드 크기가 최대값을 초과합니다"),

    // Evaluator 도메인 오류 (EVA)
    EVALUATION_ERROR("EVA001", "표현식 평가 중 오류가 발생했습니다"),
    DIVISION_BY_ZERO("EVA002", "0으로 나눌 수 없습니다"),
    UNDEFINED_VARIABLE("EVA003", "정의되지 않은 변수입니다"),
    UNSUPPORTED_OPERATOR("EVA004", "지원하지 않는 연산자입니다"),
    UNSUPPORTED_FUNCTION("EVA005", "지원하지 않는 함수입니다"),
    WRONG_ARGUMENT_COUNT("EVA006", "잘못된 인수 개수입니다"),
    UNSUPPORTED_TYPE("EVA007", "지원하지 않는 타입입니다"),
    NUMBER_CONVERSION_ERROR("EVA008", "숫자 변환 중 오류가 발생했습니다"),
    MATH_ERROR("EVA009", "수학 연산 중 오류가 발생했습니다"),
    TYPE_COMPATIBILITY_ERROR("EVA010", "타입 호환성 오류가 발생했습니다"),
    TYPE_EVALUATOR_ERROR("EVA011", "타입 평가 중 오류가 발생했습니다"),
    TYPE_ARGUMENT_ERROR("EVA012", "타입 인수 오류가 발생했습니다"),
    TYPE_CAST_ERROR("EVA013", "타입 캐스팅 오류가 발생했습니다"),
    TYPE_LOOKUP_ERROR("EVA014", "타입 조회 오류가 발생했습니다"),
    TYPE_NULL_REFERENCE_ERROR("EVA015", "타입 null 참조 오류가 발생했습니다"),
    TYPE_UNSUPPORTED_ERROR("EVA016", "지원하지 않는 타입 연산 오류가 발생했습니다"),
    TYPE_RUNTIME_ERROR("EVA017", "타입 런타임 오류가 발생했습니다"),
    EVALUATION_FAILED("EVA018", "표현식 평가에 실패했습니다"),
    EVALUATION_TIMEOUT("EVA019", "표현식 평가 시간이 초과되었습니다"),
    EVALUATION_DEPTH_EXCEEDED("EVA020", "평가 깊이가 제한을 초과했습니다"),
    EVALUATION_COMPLEXITY_EXCEEDED("EVA021", "평가 복잡도가 제한을 초과했습니다"),
    INVALID_EVALUATION_CONTEXT("EVA022", "유효하지 않은 평가 컨텍스트입니다"),
    EVALUATION_SECURITY_VIOLATION("EVA023", "평가 보안 규칙을 위반했습니다"),
    VARIABLE_NAME_INVALID("EVA024", "유효하지 않은 변수명입니다"),
    FUNCTION_EXECUTION_FAILED("EVA025", "함수 실행에 실패했습니다"),
    OPERATOR_EVALUATION_FAILED("EVA026", "연산자 평가에 실패했습니다"),
    TYPE_CONVERSION_FAILED("EVA027", "타입 변환에 실패했습니다"),
    BUILTIN_FUNCTION_ERROR("EVA028", "내장 함수 실행 중 오류가 발생했습니다"),
    EVALUATION_RESULT_INVALID("EVA029", "평가 결과가 유효하지 않습니다"),
    EVALUATION_MEMORY_EXCEEDED("EVA030", "평가 중 메모리 사용량이 초과되었습니다"),
    EVALUATION_STACK_OVERFLOW("EVA031", "평가 중 스택 오버플로가 발생했습니다"),
    EVALUATION_INFINITE_LOOP("EVA032", "평가 중 무한 루프가 감지되었습니다"),
    VARIABLE_VALUE_INVALID("EVA033", "변수 값이 유효하지 않습니다"),
    FUNCTION_ARGUMENT_INVALID("EVA034", "함수 인수가 유효하지 않습니다"),
    OPERATOR_OPERAND_INVALID("EVA035", "연산자 피연산자가 유효하지 않습니다"),
    EVALUATION_CANCELLED("EVA036", "평가가 취소되었습니다"),
    EVALUATION_INTERRUPTED("EVA037", "평가가 중단되었습니다"),

    // Calculator 도메인 오류 (CAL)
    EMPTY_FORMULA("CAL001", "수식이 비어있습니다"),
    FORMULA_TOO_LONG("CAL002", "수식이 너무 깁니다"),
    EMPTY_STEPS("CAL003", "계산 단계가 비어있습니다"),
    TOO_MANY_STEPS("CAL004", "계산 단계가 너무 많습니다"),
    TOO_MANY_VARIABLES("CAL005", "변수가 너무 많습니다"),
    MISSING_VARIABLES("CAL006", "필수 변수가 누락되었습니다"),
    STEP_EXECUTION_ERROR("CAL007", "단계 실행 중 오류가 발생했습니다"),
    FORMULA_VALIDATION_ERROR("CAL008", "수식 검증 중 오류가 발생했습니다"),
    VARIABLE_EXTRACTION_ERROR("CAL009", "변수 추출 중 오류가 발생했습니다"),
    HEALTH_CHECK_FAILED("CAL010", "핼스 체크에 실패했습니다"),
    SERIALIZATION_FAILED("CAL011", "역직렬화에 실패했습니다"),
    PERFORMANCE_WARNING("CAL012", "성능 경고가 발생했습니다"),
    VALIDATION_EXCEPTION("CAL013", "계산 유효성 검증 중 예외가 발생했습니다"),
    SESSION_ID_EMPTY("CAL014", "세션 ID는 비어있을 수 없습니다"),
    CALCULATION_HISTORY_TOO_LARGE("CAL015", "계산 이력이 최대 크기를 초과했습니다"),
    VARIABLE_NAME_EMPTY("CAL016", "변수 이름은 비어있을 수 없습니다"),
    USER_ID_EMPTY("CAL017", "사용자 ID는 비어있을 수 없습니다"),
    EMPTY_EXPRESSIONS("CAL018", "수식 목록은 비어있을 수 없습니다"),
    STEP_TIMEOUT_EXCEEDED("CAL019", "계산 단계가 전체 타임아웃을 초과했습니다"),
    REQUEST_LIST_EMPTY("CAL020", "계산 요청 목록은 비어있을 수 없습니다"),
    INVALID_CONCURRENCY_LEVEL("CAL021", "동시성 수준은 0보다 커야 합니다"),
    INVALID_BUFFER_SIZE("CAL022", "버퍼 크기는 0보다 커야 합니다"),
    MAX_RETRY_EXCEEDED("CAL023", "최대 재시도 횟수를 초과했습니다"),
    INVALID_AST_NODE_TYPE("CAL024", "유효하지 않은 AST 노드 타입입니다"),
    OPTION_KEY_EMPTY("CAL025", "옵션 키는 비어있을 수 없습니다"),
    EXECUTION_TIME_NEGATIVE("CAL026", "실행 시간은 0 이상이어야 합니다"),
    MERGE_RESULTS_EMPTY("CAL027", "병합할 결과가 없습니다"),
    STEP_NAME_EMPTY("CAL028", "단계 이름은 비어있을 수 없습니다"),
    STEP_NAME_TOO_LONG("CAL029", "단계 이름이 너무 깁니다"),
    RESULT_VARIABLE_NAME_EMPTY("CAL030", "결과 변수명은 비어있을 수 없습니다"),
    RESULT_VARIABLE_NAME_INVALID("CAL031", "결과 변수명이 유효하지 않습니다"),
    STEPS_EMPTY("CAL032", "계산 단계는 최소 1개 이상이어야 합니다"),
    STEPS_TOO_MANY("CAL033", "계산 단계가 최대 허용 개수를 초과했습니다"),
    VARIABLES_TOO_MANY("CAL034", "변수 개수가 최대 허용 개수를 초과했습니다"),
    STEP_FORMULA_EMPTY("CAL035", "단계의 수식이 비어 있습니다"),
    INDEX_OUT_OF_RANGE_INCLUSIVE("CAL036", "인덱스가 범위를 벗어났습니다(상한 포함)"),
    INDEX_OUT_OF_RANGE_EXCLUSIVE("CAL037", "인덱스가 범위를 벗어났습니다(상한 제외)"),
    MIN_STEPS_REQUIRED("CAL038", "최소 단계 개수 요건을 충족하지 못했습니다"),

    // Expresser 도메인 오류 (EXP)
    FORMATTING_ERROR("EXP001", "포맷팅 중 오류가 발생했습니다"),
    INVALID_FORMAT_OPTION("EXP002", "잘못된 포맷 옵션입니다"),
    OUTPUT_GENERATION_ERROR("EXP003", "출력 생성 중 오류가 발생했습니다"),
    INVALID_INPUT("EXP004", "잘못된 입력입니다"),
    UNSUPPORTED_STYLE("EXP005", "지원하지 않는 스타일입니다"),
    INVALID_NODE_TYPE("EXP006", "잘못된 노드 타입입니다"),

    // Annotation 도메인 오류 (ANT)
    MISSING_ENTITY_ANNOTATION("ANT001", "엔티티 어노테이션 누락"),
    ENTITY_CONTRACT_NOT_IMPLEMENTED("ANT002", "EntityCont,ract 미구현"),
    INVALID_AGGREGATE_ROOT("ANT003", "유효하지 않은 Aggregate Root"),

    // School 도메인 오류 (SCH)
    SCHOOL_INVALID_TYPE("SCH001", "유효하지 않은 학교 유형입니다"),

    // Security 도메인 오류 (SEC)
    SECURITY_INVALID_TOKEN("SEC001", "유효하지 않은 인증 토큰입니다"),
    SECURITY_UNAUTHENTICATED("SEC002", "인증되지 않은 사용자입니다"),

    //feign error
    FEIGN_SERVER_ERROR("FGN001", "외부 API 서버 오류가 발생했습니다"),

    // ExamCode 오류 (EXA)
    FAILED_GEOCODE_CONVERSION("EXA001", "주소를 변환할 수 없습니다");

    /**
     * 오류 코드의 도메인 접두사를 반환합니다.
     *
     * @return 도메인 접두사 (예: LEX, PAR, AST)
     */
    fun getDomainPrefix(): String = code.take(3)

    /**
     * 오류 코드의 숫자 부분을 반환합니다.
     *
     * @return 오류 번호 (예: 001, 002)
     */
    fun getErrorNumber(): String = code.drop(3)

    /**
     * 오류 코드가 특정 도메인에 속하는지 확인합니다.
     *
     * @param domainPrefix 확인할 도메인 접두사
     * @return 해당 도메인에 속하면 true, 아니면 false
     */
    fun belongsToDomain(domainPrefix: String): Boolean = getDomainPrefix() == domainPrefix.uppercase()
}