#!/bin/bash

# 커밋 메시지 유효성 검증
commit_msg=$(cat "$1")
regex="^(feat|fix|chore|docs|style|refactor|test|perf|ci|build|revert) \([[:space:]]*#[[:space:]]*[0-9]+[[:space:]]*\) : .+$"

if [[ "$commit_msg" =~ $regex ]]; then
    echo "✅ 커밋 메시지 형식이 올바릅니다."
else
    echo "❌ 커밋 메시지 형식이 잘못되었습니다."
    exit 1
fi

# Git 루트 디렉토리 찾기
if ! repo_root=$(git rev-parse --show-toplevel 2>/dev/null); then
    echo "❌ Git 루트 디렉토리를 찾을 수 없습니다. Git 저장소 안에서 실행해주세요."
    exit 1
fi

cd "$repo_root" || exit 1

# Gradle 빌드 검증
echo "Gradle 빌드 검증 시작..."
if ! ./gradlew clean build --no-daemon; then
    echo "❌ 빌드 실패! 커밋이 중단됩니다."
    exit 1
else
    echo "✅ 빌드 성공! 커밋 계속 진행합니다."
    exit 0
fi