object Plugins {
    const val KOTLIN_JVM = "jvm"
    const val JETBRAINS_KOTLIN_JVM = "org.jetbrains.kotlin.jvm"
    const val KOTLIN_SPRING = "plugin.spring"
    const val KOTLIN_SERIALIZATION = "plugin.serialization"
    const val JETBRAINS_KOTLIN_SERIALIZATION = "org.jetbrains.kotlin.plugin.serialization"
    const val SPRING_BOOT = "org.springframework.boot"
    const val SPRING_DEPENDENCY_MANAGEMENT = "io.spring.dependency-management"
    const val KTLINT = "org.jlleitschuh.gradle.ktlint"
    const val CASPER_CONVENTION = "casper.documentation-convention"
    const val KAPT = "kapt"
    const val PROTOBUF = "com.google.protobuf"
    const val GOOGLE_OSDETECTOR = "com.google.osdetector"
    const val ALL_OPEN = "plugin.allopen"
}