object Plugins {
    const val KOTLIN_JVM = "jvm"
    const val JETBRAINS_KOTLIN_JVM = "org.jetbrains.kotlin.jvm"
    const val KOTLIN_SPRING = "plugin.spring"
    const val KOTLIN_JPA = "plugin.jpa"
    const val KOTLIN_ALLOPEN = "plugin.allopen"
    const val KOTLIN_NOARG = "plugin.noarg"
    const val KOTLIN_KAPT = "kapt"
    const val KOTLIN_SERIALIZATION = "plugin.serialization"
    const val JETBRAINS_KOTLIN_SERIALIZATION = "org.jetbrains.kotlin.plugin.serialization"
    const val SPRING_BOOT = "org.springframework.boot"
    const val SPRING_DEPENDENCY_MANAGEMENT = "io.spring.dependency-management"
    const val KTLINT = "org.jlleitschuh.gradle.ktlint"
    const val CASPER_CONVENTION = "casper.documentation-convention"
}