package hs.kr.entrydsm.domain.evaluator.values.token

enum class Symbol(val type: Type) {
    NUMBER(type = Type.TERMINAL),
    IDENTIFIER(type = Type.TERMINAL),
    VARIABLE(type = Type.TERMINAL),
    PLUS(type = Type.TERMINAL),
    MINUS(type = Type.TERMINAL),
    MULTIPLY(type = Type.TERMINAL),
    DIVIDE(type = Type.TERMINAL),
    POWER(type = Type.TERMINAL),
    MODULO(type = Type.TERMINAL),
    EQUAL(type = Type.TERMINAL),
    NOT_EQUAL(type = Type.TERMINAL),
    LESS(type = Type.TERMINAL),
    LESS_EQUAL(type = Type.TERMINAL),
    GREATER(type = Type.TERMINAL),
    GREATER_EQUAL(type = Type.TERMINAL),
    AND(type = Type.TERMINAL),
    OR(type = Type.TERMINAL),
    NOT(type = Type.TERMINAL),
    LEFT_PAREN(type = Type.TERMINAL),
    RIGHT_PAREN(type = Type.TERMINAL),
    COMMA(type = Type.TERMINAL),
    IF(type = Type.TERMINAL),
    TRUE(type = Type.TERMINAL),
    FALSE(type = Type.TERMINAL),
    DOLLAR(type = Type.TERMINAL),

    START(type = Type.NON_TERMINAL),
    EXPR(type = Type.NON_TERMINAL),
    AND_EXPR(type = Type.NON_TERMINAL),
    COMP_EXPR(type = Type.NON_TERMINAL),
    ARITH_EXPR(type = Type.NON_TERMINAL),
    TERM(type = Type.NON_TERMINAL),
    FACTOR(type = Type.NON_TERMINAL),
    PRIMARY(type = Type.NON_TERMINAL),
    ARGS(type = Type.NON_TERMINAL),

}