name: Create Branch and PR on PR Creation

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Information
        id: pr-info
        run: |
          PR_BRANCH="${{ github.head_ref }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          # PR_BODY에 줄바꿈이 있을 수 있으므로 안전하게 처리
          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "$PR_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Setup Environment
        run: |
          chmod +x .github/scripts/setup-environment.sh
          .github/scripts/setup-environment.sh

      - name: Create Branch in Target Repository
        id: create-branch
        env:
          TARGET_REPO: "${{ secrets.TARGET_REPOSITORY }}"
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
          TARGET_BRANCH: "${{ secrets.TARGET_BRANCH || 'main' }}"
        run: |
          chmod +x .github/scripts/create-branch.sh
          BRANCH_NAME=$(.github/scripts/create-branch.sh \
            "${{ env.PR_NUMBER }}" \
            "${{ env.PR_TITLE }}" \
            "${{ env.PR_BRANCH }}" \
            "${{ secrets.TARGET_REPOSITORY }}" \
            "${{ secrets.TARGET_BRANCH || 'main' }}" \
            "${{ github.repository }}")
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create PR in Target Repository
        env:
          TARGET_REPO: "${{ secrets.TARGET_REPOSITORY }}"
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
          TARGET_BRANCH: "${{ secrets.TARGET_BRANCH || 'main' }}"
        run: |
          chmod +x .github/scripts/create-pr.sh
          .github/scripts/create-pr.sh \
            "${{ env.PR_NUMBER }}" \
            "${{ env.PR_TITLE }}" \
            "${{ env.PR_BODY }}" \
            "${{ env.BRANCH_NAME }}" \
            "${{ secrets.TARGET_REPOSITORY }}" \
            "${{ secrets.TARGET_BRANCH || 'main' }}" \
            "${{ github.repository }}"

      - name: PR Creation Result
        run: |
          echo "✅ Branch and PR created in target repository"
          echo "Target Repository: ${{ secrets.TARGET_REPOSITORY }}"
          echo "Branch Name: ${{ env.BRANCH_NAME }}"
